// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjxccdpfhlqpurosjuvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqeGNjZHBmaGxxcHVyb3NqdXZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTgzODEsImV4cCI6MjA3Mzg3NDM4MX0.JSIc2h_LHv7A5f9m6dxDT1isDpdIPViJRE8NrSHjeEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});